# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gz7r3WM_6CLYIHYVxCrQxzF59_gMLCRO
"""

# Install libraries
pip install tensorflow matplotlib -q

import tensorflow as tf
import matplotlib.pyplot as plt
import os

# Download Pix2Pix dataset (Facades)
dataset_url = "http://efrosgans.eecs.berkeley.edu/pix2pix/datasets/facades.tar.gz"

path = tf.keras.utils.get_file(
    'facades.tar.gz',
    origin=dataset_url,
    extract=True)

# Corrected PATH construction: The extracted tar.gz typically creates a 'facades' directory inside the 'path' returned by get_file.
PATH = os.path.join(path, 'facades')

train_path = PATH + '/train'
test_path = PATH + '/test'

# Image size
IMG_WIDTH = 256
IMG_HEIGHT = 256

# Load images
def load_image(image_file):

    image = tf.io.read_file(image_file)
    image = tf.image.decode_jpeg(image)

    w = tf.shape(image)[1] // 2

    input_image = image[:, :w, :]
    real_image = image[:, w:, :]

    input_image = tf.image.resize(input_image,[256,256])
    real_image = tf.image.resize(real_image,[256,256])

    input_image = (input_image / 127.5) - 1
    real_image = (real_image / 127.5) - 1

    return input_image, real_image


# Load dataset
train_dataset = tf.data.Dataset.list_files(train_path + '/*.jpg')
train_dataset = train_dataset.map(load_image).batch(1)

test_dataset = tf.data.Dataset.list_files(test_path + '/*.jpg')
test_dataset = test_dataset.map(load_image).batch(1)


# Downsample block
def downsample(filters,size):

    initializer = tf.random_normal_initializer(0.,0.02)

    result = tf.keras.Sequential()
    result.add(
        tf.keras.layers.Conv2D(filters,size,strides=2,padding='same',
                               kernel_initializer=initializer,use_bias=False))
    result.add(tf.keras.layers.BatchNormalization())
    result.add(tf.keras.layers.LeakyReLU())

    return result


# Upsample block
def upsample(filters,size):

    initializer = tf.random_normal_initializer(0.,0.02)

    result = tf.keras.Sequential()
    result.add(
        tf.keras.layers.Conv2DTranspose(filters,size,strides=2,padding='same',
                                        kernel_initializer=initializer,use_bias=False))
    result.add(tf.keras.layers.BatchNormalization())
    result.add(tf.keras.layers.ReLU())

    return result


# Generator (U-Net)
def Generator():

    inputs = tf.keras.layers.Input(shape=[256,256,3])

    down_stack = [
        downsample(64,4),
        downsample(128,4),
        downsample(256,4),
        downsample(512,4)
    ]

    up_stack = [
        upsample(256,4),
        upsample(128,4),
        upsample(64,4)
    ]

    x = inputs
    skips = []

    for down in down_stack:
        x = down(x)
        skips.append(x)

    skips = reversed(skips[:-1])

    for up,skip in zip(up_stack,skips):
        x = up(x)
        x = tf.keras.layers.Concatenate()([x,skip])

    last = tf.keras.layers.Conv2DTranspose(
        3,4,strides=2,padding='same',activation='tanh')

    x = last(x)

    return tf.keras.Model(inputs=inputs,outputs=x)


generator = Generator()


# Discriminator (PatchGAN)
def Discriminator():

    initializer = tf.random_normal_initializer(0.,0.02)

    inp = tf.keras.layers.Input(shape=[256,256,3])
    tar = tf.keras.layers.Input(shape=[256,256,3])

    x = tf.keras.layers.concatenate([inp,tar])

    down1 = downsample(64,4)(x)
    down2 = downsample(128,4)(down1)
    down3 = downsample(256,4)(down2)

    zero_pad1 = tf.keras.layers.ZeroPadding2D()(down3)

    conv = tf.keras.layers.Conv2D(
        512,4,strides=1,kernel_initializer=initializer,use_bias=False)(zero_pad1)

    batchnorm1 = tf.keras.layers.BatchNormalization()(conv)

    leaky_relu = tf.keras.layers.LeakyReLU()(batchnorm1)

    zero_pad2 = tf.keras.layers.ZeroPadding2D()(leaky_relu)

    last = tf.keras.layers.Conv2D(
        1,4,strides=1,kernel_initializer=initializer)(zero_pad2)

    return tf.keras.Model(inputs=[inp,tar],outputs=last)


discriminator = Discriminator()


# Loss functions
loss_object = tf.keras.losses.BinaryCrossentropy(from_logits=True)

def generator_loss(disc_generated_output,gen_output,target):

    gan_loss = loss_object(tf.ones_like(disc_generated_output),
                           disc_generated_output)

    l1_loss = tf.reduce_mean(tf.abs(target-gen_output))

    return gan_loss + (100*l1_loss)


def discriminator_loss(disc_real_output,disc_generated_output):

    real_loss = loss_object(tf.ones_like(disc_real_output),
                            disc_real_output)

    generated_loss = loss_object(tf.zeros_like(disc_generated_output),
                                 disc_generated_output)

    return real_loss + generated_loss


# Optimizers
generator_optimizer = tf.keras.optimizers.Adam(2e-4,beta_1=0.5)
discriminator_optimizer = tf.keras.optimizers.Adam(2e-4,beta_1=0.5)


# Training step
@tf.function
def train_step(input_image,target):

    with tf.GradientTape() as gen_tape, tf.GradientTape() as disc_tape:

        gen_output = generator(input_image,training=True)

        disc_real_output = discriminator([input_image,target],training=True)

        disc_generated_output = discriminator([input_image,gen_output],training=True)

        gen_loss = generator_loss(disc_generated_output,gen_output,target)

        disc_loss = discriminator_loss(disc_real_output,disc_generated_output)

    generator_gradients = gen_tape.gradient(gen_loss,
                                            generator.trainable_variables)

    discriminator_gradients = disc_tape.gradient(disc_loss,
                                                 discriminator.trainable_variables)

    generator_optimizer.apply_gradients(zip(generator_gradients,
                                            generator.trainable_variables))

    discriminator_optimizer.apply_gradients(zip(discriminator_gradients,
                                               discriminator.trainable_variables))


# Train model
EPOCHS = 2

for epoch in range(EPOCHS):

    for input_image,target in train_dataset.take(100):
        train_step(input_image,target)

    print("Epoch",epoch+1,"completed")


# Generate output
for example_input,example_target in test_dataset.take(1):

    prediction = generator(example_input,training=True)

    plt.figure(figsize=(12,4))

    display_list = [example_input[0],example_target[0],prediction[0]]
    title = ['Input Image','Real Image','Generated Image']

    for i in range(3):
        plt.subplot(1,3,i+1)
        plt.title(title[i])
        plt.imshow((display_list[i]+1)/2)
        plt.axis('off')

    plt.show()

